# Generated by Django 3.2.4 on 2021-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='MCQ', max_length=5),
            preserve_default=False,
        ),
    ]
