# Generated by Django 3.2.4 on 2021-06-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ongoing',
            old_name='saved_choices',
            new_name='saved_choice',
        ),
    ]
