# Generated by Django 3.2.4 on 2021-06-28 12:23

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoing',
            name='ongoing_id',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.UUIDField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_id',
            field=models.UUIDField(default=datetime.datetime(2021, 6, 28, 12, 23, 40, 458679, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
