# Generated by Django 3.2.4 on 2021-06-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210628_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='ongoing_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.ongoing'),
        ),
    ]
