# Generated by Django 3.2.4 on 2021-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_saved_choices_ongoing_saved_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_desc',
            field=models.CharField(default='This is a quiz description', max_length=300),
            preserve_default=False,
        ),
    ]
