# Generated by Django 3.2.4 on 2021-06-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple choice'), ('FIB', 'fill in the blanks')], max_length=5),
        ),
    ]
