# Generated by Django 3.2.5 on 2021-07-07 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_question_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FIB_Question',
            new_name='FibQuestion',
        ),
        migrations.RenameModel(
            old_name='MCQ_Question',
            new_name='McqQuestion',
        ),
        migrations.RenameModel(
            old_name='users_answer',
            new_name='UsersAnswer',
        ),
    ]
