# Generated by Django 3.2.5 on 2021-07-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210707_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquestion',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='taken',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='taken',
            name='username',
        ),
        migrations.RemoveField(
            model_name='usersanswer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='usersanswer',
            name='username',
        ),
        migrations.DeleteModel(
            name='FibQuestion',
        ),
        migrations.DeleteModel(
            name='McqQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Taken',
        ),
        migrations.DeleteModel(
            name='UsersAnswer',
        ),
    ]
